project_id = "kxcqizfxfqzmnhxeaepc"

[functions]
  [functions.activate-subscription]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.cancel-subscription]
    verify_jwt = false
  [functions.evolution-webhook]
    verify_jwt = false
  [functions.reactivate-subscription]
    verify_jwt = false
  [functions.whatsapp-ai-handler]
    verify_jwt = false
