name: Deploy (Stage/Prod)

on:
  workflow_run:
    workflows: ["Robot Tests (Playwright + Docker)"]
    types: [completed]
    branches: [main, develop]

  workflow_dispatch:
    inputs:
      environment:
        description: "Escolha o ambiente"
        required: true
        type: choice
        options:
          - stage
          - prod

jobs:
  deploy:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Build (staging)
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'develop') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'stage') }}
        run: npm run build -- --mode staging

      - name: Build (production)
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod') }}
        run: npm run build -- --mode production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy STAGE
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'develop') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'stage') }}
        run: |
          aws s3 sync dist s3://pawfect-setup-stage --delete
          aws s3 cp dist/index.html s3://pawfect-setup-stage/index.html \
            --cache-control "public, max-age=0, must-revalidate" \
            --content-type "text/html" \
            --metadata-directive REPLACE
          aws cloudfront create-invalidation --distribution-id E3JF2XH858TUI8 --paths "/*"

      - name: Deploy PROD
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod') }}
        run: |
          aws s3 sync dist s3://pawfect-setup-prod --delete
          aws s3 cp dist/index.html s3://pawfect-setup-prod/index.html \
            --cache-control "public, max-age=0, must-revalidate" \
            --content-type "text/html" \
            --metadata-directive REPLACE
          aws cloudfront create-invalidation --distribution-id E133YQTNLCUGEM --paths "/*"